remote_theme: just-the-docs/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
#logo: "https://avatars.githubusercontent.com/u/18517307?s=400&u=7b940e944090c176784840acd522299769a43290&v=4"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Celerium":
    - "https://celerium.org/"
  "GitHub":
    - "https://github.com/Celerium/urban-fortnight"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true